### ISSUE TITLE
文件夹名称大小写问题

### ISSUE THREAD

**Issue by menzil** [SilvaQ/react-antd-reference#49]
react-antd-reference/src/routes/index.js
下载安装依赖运行了一下，提示文件找不到错误。看一下代码好像是文件夹名称大小写区分引起的。这个需要规范一下。

**Comment by SilvaQ** [comment]
这项目我直接接入公司项目后 没在这边同步，有了很多比较打的调整。
目前如果你感兴趣的话先了解了解就好。之前都是在学习 有些东西不那么理想。
现在我接入公司的那个相当ok 了的。但是没法分享。 

我吧公司项目处理完后 打算把里面的核心调整拿出来，完善一下github上的这个。

**Comment by SilvaQ** [comment]
@menzil  我以现状为准调整并修复了一下问题，你拉去最新的运行看一下吧.

**Comment by menzil** [comment]
> @menzil 我以现状为准调整并修复了一下问题，你拉去最新的运行看一下吧.

嗯，能正常运行了。
好的，谢谢！
